---
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init_flag.yaml"

- name: Check if Config dir exists
  stat:
    path: "{{ morla_qbittorrent_config_dir }}"
  register: check_qbittorrent_config_dir


