---
    - name: Check if Config dir exists
      stat:
          path: '{{ morla_qbittorrent_config_dir }}'
      register: check_qbittorrent_config_dir

    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_qbittorrent_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_qbittorrent_config_dir.stat.exists

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_qbittorrent_container_name }}'
          image: '{{ morla_qbittorrent_container_image}}'
          network: morla-wireguard-network
          network_aliases: '{{ morla_qbittorrent_short_name }}'
          ports: '{{ morla_qbittorrent_ports }}'
          volumes: '{{ morla_qbittorrent_volumes }}'
          label: '{{ morla_qbittorrent_labels }}'
          env:
              PUID: '{{ morla_root_puid }}'
              PGID: '{{ morla_root_pgid }}'
              TZ: '{{ morla_tz }}'
              WEBUI_PORT: '{{ morla_qbittorrent_env_webui_port }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
