---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for pyload_ng
morla_pyload_ng_enabled: false

morla_pyload_ng_flag_public: false
morla_pyload_ng_flag_autostart: true
morla_pyload_ng_flag_wireguard: true
morla_pyload_ng_flag_firewall: true # replace with if port list non empty

# Name
morla_pyload_ng_long_name: PyloadNG
morla_pyload_ng_short_name: pyload-ng

morla_pyload_ng_container_short_name: '{{ morla_pyload_ng_short_name }}'
morla_pyload_ng_container_name: '{{ morla_user_username }}-{{ morla_pyload_ng_container_short_name }}'
morla_pyload_ng_public_url: '{{ morla_pyload_ng_short_name }}.{{ morla_public_url }}'

morla_pyload_ng_container_image_base: lscr.io/linuxserver/pyload-ng
morla_pyload_ng_container_image_tag: latest
morla_pyload_ng_container_image: '{{ morla_pyload_ng_container_image_base }}:{{ morla_pyload_ng_container_image_tag }}'

# Networking
morla_pyload_ng_reverse_proxy_port: '8000'
morla_pyload_ng_exposed_proxy_port: '{{ morla_pyload_ng_reverse_proxy_port }}'

# Networking/Firewall
morla_pyload_ng_fw_ports:
    tcp:
        - '{{ morla_pyload_ng_reverse_proxy_port }}'
        - '9666'
    udp:

# Networking/Port Forwarding
morla_pyload_ng_ports:
    - '{{ morla_pyload_ng_reverse_proxy_port }}:{{ morla_pyload_ng_exposed_proxy_port }}'
    - '{{ morla_pyload_ng_fw_ports.tcp[1] }}:{{ morla_pyload_ng_fw_ports.tcp[1] }}'

# Storage/Host
morla_pyload_ng_config_dir: '{{ morla_config_dir }}/{{ morla_pyload_ng_long_name }}'
morla_pyload_ng_downloads_dir: '{{ morla_pyload_dir }}'

# Storage/Mount
morla_pyload_ng_volumes:
    - '{{ morla_pyload_ng_config_dir }}:/config:Z'
    - '{{ morla_pyload_ng_downloads_dir }}:/downloads:z'

# Labels/Traefik
morla_pyload_ng_labels:
    traefik.enable: '{{ morla_pyload_ng_flag_public }}'
    traefik.http.services.pyload_ng.loadbalancer.server.port: '{{ morla_pyload_ng_exposed_proxy_port }}'
    traefik.http.routers.pyload_ng.tls: true
    traefik.http.routers.pyload_ng.rule: Host(`{{ morla_pyload_ng_public_url }}`)
    traefik.http.routers.pyload_ng.entrypoints: websecure
    traefik.http.routers.pyload_ng.tls.certresolver: myresolver
    traefik.http.routers.pyload_ng.tls.domains: '{{ morla_pyload_ng_public_url }}'
    traefik.http.routers.pyload_ng.middlewares: wireguard-ipwhitelist@file
