- name: Open TCP ports for Transmission
  become: yes
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  loop: "{{ morla_transmission_fw_ports.tcp }}"

      
- name: Open UDP ports for Transmission
  become: yes
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: enabled
    immediate: true
  loop: "{{ morla_transmission_fw_ports.udp }}"
