---
# roles/transmission/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      tags:
          - setup-all
          - setup-transmission

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_transmission.yml'
      when: morla_transmission_enabled | bool
      tags:
          - setup-all
          - setup-transmission

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_transmission.yml'
      when: morla_transmission_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-transmission

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_transmission.yml'
      when: morla_transmission_enabled | bool
      tags:
          - setup-all
          - setup-transmission
