---
# roles/cloudflared/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      tags:
          - always
          - setup-all
          - setup-cloudflared
          - setup-network

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_cloudflared.yml'
      tags:
          - setup-all
          - setup-cloudflared
          - setup-network

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_cloudflared.yml'
      tags:
          - never
          - destroy-all
          - destroy-cloudflared
          - destroy-network

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_cloudflared.yml'
      tags:
          - setup-all
          - setup-cloudflared
          - setup-network
