---
# - name: Add Container to the list of autostart containers
#   ansible.builtin.set_fact:
#     morla_systemd_autostart_containers: "{{ morla_systemd_autostart_containers  + [ morla_nginx_wireguard_container_name ] }} "

- name: Check if NginxWireguard Config dir exists
  stat:
    path: "{{ morla_nginx_wireguard_config_dir }}"
  register: check_nginx_wireguard_config_dir

- name: Create config directory
  ansible.builtin.file:
    path: "{{ morla_nginx_wireguard_config_dir }}"
    state: directory
    owner: "{{ morla_user_username }}"
    group: "{{ morla_user_groupname }}"
  when: not check_nginx_wireguard_config_dir.stat.exists

