# roles/morla-systemd/tasks/main.yml

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yaml"
  tags:
    - always

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_systemd.yaml"
  tags:
    - setup-all
    - setup-systemd
