---
# roles/gitea/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      when: morla_gitea_enabled | bool
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      when: morla_gitea_enabled | bool
      tags:
          - always
          - setup-all
          - setup-gitea

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_gitea.yml'
      when: morla_gitea_enabled | bool
      tags:
          - setup-all
          - setup-gitea

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_gitea.yml'
      when: morla_gitea_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-gitea

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_gitea.yml'
      when: morla_gitea_enabled | bool
      tags:
          - setup-all
          - setup-gitea
