---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for ghost
morla_ghost_enabled: false

morla_ghost_flag_public: true
morla_ghost_flag_autostart: true
morla_ghost_flag_wireguard: true
morla_ghost_flag_firewall: true # replace with if port list non empty

# Name
morla_ghost_long_name: Ghost
morla_ghost_short_name: ghost

morla_ghost_container_short_name: '{{ morla_ghost_short_name }}'
morla_ghost_container_name: '{{ morla_user_username }}-{{ morla_ghost_container_short_name }}'
morla_ghost_public_url: '{{ morla_ghost_short_name }}.{{ morla_public_url }}'

morla_ghost_pod_name: '{{ morla_ghost_container_name }}-pod'

morla_ghost_container_image_base: docker.io/library/ghost
morla_ghost_container_image_tag: latest
morla_ghost_container_image: '{{ morla_ghost_container_image_base }}:{{ morla_ghost_container_image_tag }}'

# Networking
morla_ghost_reverse_proxy_port: '2368'
morla_ghost_exposed_proxy_port: '{{ morla_ghost_reverse_proxy_port }}'

# Networking/Firewall
morla_ghost_fw_ports:
    tcp:
        - '{{ morla_ghost_reverse_proxy_port }}'
    udp:

# Networking/Port Forwarding
morla_ghost_ports:
    - '{{ morla_ghost_reverse_proxy_port }}:{{ morla_ghost_exposed_proxy_port }}'

# Storage/Host
morla_ghost_config_dir: '{{ morla_config_dir }}/{{ morla_ghost_long_name }}'
morla_ghost_data_dir: '{{ morla_data_dir }}'

# Storage/Mount
morla_ghost_volumes:
    - '{{ morla_ghost_config_dir }}:/var/lib/ghost/content:Z'

# Labels/Traefik
morla_ghost_labels:
    traefik.enable: '{{ morla_ghost_flag_public }}'
    traefik.http.services.ghost.loadbalancer.server.port: '{{ morla_ghost_exposed_proxy_port }}'
    traefik.http.routers.ghost.tls: true
    traefik.http.routers.ghost.rule: Host(`{{ morla_ghost_public_url }}`)
    traefik.http.routers.ghost.entrypoints: websecure
    traefik.http.routers.ghost.tls.certresolver: myresolver

# DB
# Name
morla_ghost_db_long_name: GhostDB
morla_ghost_db_short_name: ghost-db

morla_ghost_db_container_short_name: '{{ morla_ghost_db_short_name }}'
morla_ghost_db_container_name: '{{ morla_user_username }}-{{ morla_ghost_db_container_short_name }}'

morla_ghost_db_container_image_base: lscr.io/linuxserver/mariadb
morla_ghost_db_container_image_tag: 10.6.10
morla_ghost_db_container_image: '{{ morla_ghost_db_container_image_base }}:{{ morla_ghost_db_container_image_tag }}'

# Environment
morla_ghost_db_env_mysql_root_password: '{{ morla_ghost_db_password}}'
morla_ghost_db_env_mysql_database: ghost-db

# Storage/Host
morla_ghost_db_config_dir: '{{ morla_config_dir }}/{{ morla_ghost_db_long_name }}'

# Storage/Mount
morla_ghost_db_volumes:
    - '{{ morla_ghost_db_config_dir }}:/config:Z'
