---
    - name: Wait until the file nginx.conf is present before continuing
      ansible.builtin.wait_for:
          path: '{{ morla_nginx_config_dir }}/nginx/nginx.conf'

    - name: Create Main Nginx Config
      ansible.builtin.template:
    #mode: "0664"
          src: nginx.conf.j2
          dest: '{{ morla_nginx_site_confs }}/nginx.conf'

    - name: Create Reverse Proxy Nginx Config
      ansible.builtin.template:
    #mode: "0664"
          src: '{{ item }}.conf.j2'
          dest: '{{ morla_nginx_site_confs }}/{{ item }}.{{ morla_subdomain }}.{{ morla_domain }}.conf'
      loop: '{{ morla_public_domains }}'
