---
# roles/transfersh/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      when: morla_transfersh_enabled | bool
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      when: morla_transfersh_enabled | bool
      tags:
          - always
          - setup-all
          - setup-transfersh

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_transfersh.yml'
      when: morla_transfersh_enabled | bool
      tags:
          - setup-all
          - setup-transfersh

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_transfersh.yml'
      when: morla_transfersh_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-transfersh

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_transfersh.yml'
      when: morla_transfersh_enabled | bool
      tags:
          - setup-all
          - setup-transfersh
