---
#    - name: Create config directory
#      ansible.builtin.file:
#          path: '{{ morla_transfersh_config_dir }}'
#          state: directory
#          owner: '{{ morla_user_username }}'
#          group: '{{ morla_user_groupname }}'
#      when: not check_transfersh_config_dir.stat.exists

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_transfersh_container_name }}'
          image: '{{ morla_transfersh_container_image}}'
          network: morla-wireguard-network
          network_aliases: '{{ morla_transfersh_short_name }}'
          ports: '{{ morla_transfersh_ports }}'
          volumes: '{{ morla_transfersh_volumes }}'
          label: '{{ morla_transfersh_labels }}'
          command: '{{ morla_transfersh_command }}'
          env:
              HTTP_AUTH_USER: '{{ morla_transfersh_env_http_auth_user }}'
              HTTP_AUTH_PASS: '{{ morla_transfersh_env_http_auth_pass }}'
              HTTP_AUTH_IP_WHITELIST: '{{ morla_transfersh_env_http_auth_ip_whitelist }}'
              RATE_LIMIT: '{{ morla_transfersh_env_rate_limit }}'
              PURGE_DAYS: '{{ morla_transfersh_env_purge_days }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
