- name: Restart Morla Wireguard Pod
  containers.podman.podman_pod:
    name: morla-wireguard-pod
    state: restarted
    network:
      - morla-wireguard-network
    ports: "{{ morla_wireguard_ports }}"
    ip: "172.20.0.66"
    generate_systemd:
      path: "{{ morla_home_config_systemd_dir }}"
      restart_policy: always
      names: true
    uidmap:
      - "{{ morla_fake_puid }}:0:1"
      - "0:1:{{ morla_fake_puid }}"
      - "{{ morla_fake_puid + 1 }}:{{ morla_fake_puid + 1 }}:{{ morla_subuid_size - morla_fake_puid }}"
    gidmap:
      - "{{ morla_fake_pgid }}:0:1"
      - "0:1:{{ morla_fake_pgid }}"
      - "{{ morla_fake_pgid + 1 }}:{{ morla_fake_pgid + 1 }}:{{ morla_subgid_size - morla_fake_pgid }}"
