---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for grav
morla_grav_enabled: false

morla_grav_flag_public: false
morla_grav_flag_autostart: true
morla_grav_flag_wireguard: true
morla_grav_flag_firewall: true # replace with if port list non empty

# Name
morla_grav_long_name: Grav
morla_grav_short_name: grav

morla_grav_container_short_name: '{{ morla_grav_short_name }}'
morla_grav_container_name: '{{ morla_user_username }}-{{ morla_grav_container_short_name }}'
morla_grav_public_url: '{{ morla_grav_short_name }}.{{ morla_public_url }}'

morla_grav_container_image_base: lscr.io/linuxserver/grav
morla_grav_container_image_tag: latest
morla_grav_container_image: '{{ morla_grav_container_image_base }}:{{ morla_grav_container_image_tag }}'

# Networking
morla_grav_reverse_proxy_port: '22331'
morla_grav_exposed_proxy_port: '{{ morla_grav_reverse_proxy_port }}'

# Networking/Firewall
morla_grav_fw_ports:
    tcp:
        - '{{ morla_grav_reverse_proxy_port }}'
    udp:

# Networking/Port Forwarding
morla_grav_ports:
    - '{{ morla_grav_reverse_proxy_port }}:80'

# Storage/Host
morla_grav_config_dir: '{{ morla_config_dir }}/{{ morla_grav_long_name }}'
morla_grav_data_dir: '{{ morla_data_dir }}'

# Storage/Mount
morla_grav_volumes:
    - '{{ morla_grav_config_dir }}:/config:Z'
    - '{{ morla_grav_data_dir }}:/data:z'

# Labels/Traefik
morla_grav_labels:
    traefik.enable: '{{ morla_grav_flag_public }}'
    traefik.http.services.grav.loadbalancer.server.port: '{{ morla_grav_exposed_proxy_port }}'
    traefik.http.routers.grav.tls: true
    traefik.http.routers.grav.rule: Host(`{{ morla_grav_public_url }}`)
    traefik.http.routers.grav.entrypoints: websecure
    traefik.http.routers.grav.tls.certresolver: myresolver
    traefik.http.routers.grav.tls.domains: '{{ morla_grav_public_url }}'
