---
# roles/homarr/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      when: morla_homarr_enabled | bool
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      when: morla_homarr_enabled | bool
      tags:
          - always
          - setup-all
          - setup-homarr

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_homarr.yml'
      when: morla_homarr_enabled | bool
      tags:
          - setup-all
          - setup-homarr

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_homarr.yml'
      when: morla_homarr_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-homarr

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_homarr.yml'
      when: morla_homarr_enabled | bool
      tags:
          - setup-all
          - setup-homarr
