---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for lidarr
morla_lidarr_enabled: false

morla_lidarr_flag_public: false
morla_lidarr_flag_autostart: true
morla_lidarr_flag_wireguard: true
morla_lidarr_flag_firewall: true # replace with if port list non empty

# Name
morla_lidarr_long_name: Lidarr
morla_lidarr_short_name: lidarr

morla_lidarr_container_short_name: '{{ morla_lidarr_short_name }}'
morla_lidarr_container_name: '{{ morla_user_username }}-{{ morla_lidarr_container_short_name }}'
morla_lidarr_public_url: '{{ morla_lidarr_short_name }}.{{ morla_public_url }}'

morla_lidarr_container_image_base: cr.hotio.dev/hotio/lidarr
morla_lidarr_container_image_tag: latest
morla_lidarr_container_image: '{{ morla_lidarr_container_image_base }}:{{ morla_lidarr_container_image_tag }}'

# Networking
morla_lidarr_reverse_proxy_port: '8686'
morla_lidarr_exposed_proxy_port: '{{ morla_lidarr_reverse_proxy_port }}'

# Networking/Firewall
morla_lidarr_fw_ports:
    tcp:
        - '{{ morla_lidarr_reverse_proxy_port }}'
    udp:

# Networking/Port Forwarding
morla_lidarr_ports:
    - '{{ morla_lidarr_reverse_proxy_port }}:{{ morla_lidarr_exposed_proxy_port }}'

# Storage/Host
morla_lidarr_config_dir: '{{ morla_config_dir }}/{{ morla_lidarr_long_name }}'
morla_lidarr_data_dir: '{{ morla_media_dir }}'

# Storage/Mount
morla_lidarr_volumes:
    - '{{ morla_lidarr_config_dir }}:/config:Z'
    - '{{ morla_lidarr_data_dir }}:/data/media:z'
    - '{{ morla_torrents_dir }}:/data/torrents:z'

# Labels/Traefik
morla_lidarr_labels:
    traefik.enable: '{{ morla_lidarr_flag_public }}'
    traefik.http.services.lidarr.loadbalancer.server.port: '{{ morla_lidarr_exposed_proxy_port }}'
    traefik.http.routers.lidarr.tls: true
    traefik.http.routers.lidarr.rule: Host(`{{ morla_lidarr_public_url }}`)
    traefik.http.routers.lidarr.entrypoints: websecure
    traefik.http.routers.lidarr.tls.certresolver: myresolver
    traefik.http.routers.lidarr.tls.domains: '{{ morla_lidarr_public_url }}'
