---
    - name: Check if Config dir exists
      stat:
          path: '{{ morla_photostructure_config_dir }}'
      register: check_photostructure_config_dir

    - name: Check if Library dir exists
      stat:
          path: '{{ morla_photostructure_library_dir }}'
      register: check_photostructure_library_dir

    - name: Check if Logs dir exists
      stat:
          path: '{{ morla_photostructure_logs_dir }}'
      register: check_photostructure_logs_dir

    - name: Check if Temp dir exists
      stat:
          path: '{{ morla_photostructure_tmp_dir }}'
      register: check_photostructure_tmp_dir

    - name: Check if Pictures dir exists
      stat:
          path: '{{ morla_photostructure_pictures_dir }}'
      register: check_photostructure_pictures_dir
