---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for coredns
morla_coredns_enabled: false

morla_coredns_flag_public: false
morla_coredns_flag_autostart: true
morla_coredns_flag_wireguard: true
morla_coredns_flag_firewall: true # replace with if port list non empty

# Name
morla_coredns_long_name: CoreDNS
morla_coredns_short_name: coredns

morla_coredns_container_short_name: '{{ morla_coredns_short_name }}'
morla_coredns_container_name: '{{ morla_user_username }}-{{ morla_coredns_container_short_name }}'
morla_coredns_public_url: '{{ morla_coredns_short_name }}.{{ morla_public_url }}'
morla_coredns_tailscale_url: '{{ morla_coredns_short_name }}.{{ morla_tailscale_url }}'

morla_coredns_container_image_base: docker.io/coredns/coredns
morla_coredns_container_image_tag: latest
morla_coredns_container_image: '{{ morla_coredns_container_image_base }}:{{ morla_coredns_container_image_tag }}'

morla_coredns_cap_drop:
    - ALL

morla_coredns_cap_add:
    - NET_BIND_SERVICE

# Networking
morla_coredns_reverse_proxy_port: '53'
morla_coredns_exposed_proxy_port: '53'

# Networking/Firewall
morla_coredns_fw_ports:
    tcp:
        - '{{ morla_coredns_reverse_proxy_port }}'
    udp:
        - '{{ morla_coredns_reverse_proxy_port }}'

# Networking/Port Forwarding
morla_coredns_ports:
    - '{{ morla_coredns_fw_ports.tcp[0] }}:{{ morla_coredns_exposed_proxy_port }}/tcp'
    - '{{ morla_coredns_fw_ports.udp[0] }}:{{ morla_coredns_exposed_proxy_port }}/udp'

# Storage/Host
morla_coredns_config_dir: '{{ morla_config_dir }}/{{ morla_coredns_long_name }}'

# Storage/Mount
morla_coredns_volumes:
    - '{{ morla_coredns_config_dir }}:/etc/coredns:Z,ro'

# Labels/Traefik
morla_coredns_labels:
    traefik.enable: '{{ morla_coredns_flag_public }}'
    traefik.http.services.coredns.loadbalancer.server.port: '{{ morla_coredns_exposed_proxy_port }}'
    traefik.http.routers.coredns.tls: true
    traefik.http.routers.coredns.rule: Host(`{{ morla_coredns_tailscale_url }}`)
    traefik.http.routers.coredns.entrypoints: websecure
    traefik.http.routers.coredns.tls.certresolver: myresolver
    traefik.http.routers.coredns.tls.domains: '{{ morla_coredns_tailscale_url }}'
