---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_radarr_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_radarr_config_dir.stat.exists

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_radarr_container_name }}'
          image: '{{ morla_radarr_container_image}}'
          network: morla-wireguard-network
          network_aliases: '{{ morla_radarr_short_name }}'
          ports: '{{ morla_radarr_ports }}'
          volumes: '{{ morla_radarr_volumes }}'
          label: '{{ morla_radarr_labels }}'
          dns:
            - 1.1.1.1
          env:
              PUID: '{{ morla_fake_puid }}'
              PGID: '{{ morla_fake_pgid }}'
              TZ: '{{ morla_tz }}'
          userns: keep-id:uid={{ morla_fake_puid }},gid={{ morla_fake_pgid }}
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
