morla_transmission_enabled: true
morla_transmission_become: true

morla_transmission_flag_public: false
morla_transmission_flag_autostart: true
morla_transmission_flag_wireguard: true
morla_transmission_flag_firewall: true # replace with if port list non empty

morla_transmission_long_name: "Transmission"
morla_transmission_short_name: transmission

morla_transmission_container_short_name: "{{ morla_transmission_short_name }}"
morla_transmission_container_name: "{{ morla_user_username }}-{{ morla_transmission_container_short_name }}"

morla_transmission_public_url: "{{ morla_transmission_short_name }}.{{ morla_public_url }}"

# filesystem dir for configs
morla_transmission_config_dir: "{{ morla_config_dir }}/{{ morla_transmission_long_name }}"
morla_transmission_torrents_dir: "{{ morla_torrents_dir }}"

morla_transmission_container_image_base: "lscr.io/linuxserver/transmission"
morla_transmission_container_image_tag: "latest"
morla_transmission_container_image: "{{ morla_transmission_container_image_base }}:{{ morla_radarr_container_image_tag }}"

morla_transmission_web_home: "/flood-for-transmission/"

# used inside container config
morla_transmission_reverse_proxy_port: "9091"

morla_transmission_fw_ports:
  tcp:
    - "{{ morla_transmission_reverse_proxy_port }}"
    - "51413"
  udp:
    - "51413"

morla_transmission_ports:
  - "{{ morla_transmission_fw_ports.tcp[0] }}:{{ morla_transmission_fw_ports.tcp[0] }}"
  - "{{ morla_transmission_fw_ports.tcp[1] }}:{{ morla_transmission_fw_ports.tcp[1] }}"
  - "{{ morla_transmission_fw_ports.udp[0] }}:{{ morla_transmission_fw_ports.udp[0] }}/udp"

morla_transmission_volumes:
  - "{{ morla_transmission_config_dir }}:/config:Z"
  - "{{ morla_transmission_torrents_dir }}:/data/torrents"
