---
# roles/etebase/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      when: morla_etebase_enabled | bool
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      when: morla_etebase_enabled | bool
      tags:
          - always
          - setup-all
          - setup-etebase

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_etebase.yml'
      when: morla_etebase_enabled | bool
      tags:
          - setup-all
          - setup-etebase

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_etebase.yml'
      when: morla_etebase_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-etebase

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_etebase.yml'
      when: morla_etebase_enabled | bool
      tags:
          - setup-all
          - setup-etebase
