---
# roles/pyload/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      when: morla_pyload_enabled | bool
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      when: morla_pyload_enabled | bool
      tags:
          - always
          - setup-all
          - setup-pyload

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_pyload.yml'
      when: morla_pyload_enabled | bool
      tags:
          - setup-all
          - setup-pyload

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_pyload.yml'
      when: morla_pyload_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-pyload

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_pyload.yml'
      when: morla_pyload_enabled | bool
      tags:
          - setup-all
          - setup-pyload
