---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_pyload_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_pyload_config_dir.stat.exists

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_pyload_container_name }}'
          image: '{{ morla_pyload_container_image}}'
          network: morla-wireguard-network
          network_aliases: '{{ morla_pyload_short_name }}'
          ports: '{{ morla_pyload_ports }}'
          volumes: '{{ morla_pyload_volumes }}'
          label: '{{ morla_pyload_labels }}'
          env:
              PUID: '{{ morla_fake_puid }}'
              PGID: '{{ morla_fake_pgid }}'
              TZ: '{{ morla_tz }}'
          uidmap:
              - '{{ morla_fake_puid }}:0:1'
              - 0:1:{{ morla_fake_puid }}
              - '{{ morla_fake_puid + 1 }}:{{ morla_fake_puid + 1 }}:{{ morla_subuid_size - morla_fake_puid }}'
          gidmap:
              - '{{ morla_fake_pgid }}:0:1'
              - 0:1:{{ morla_fake_pgid }}
              - '{{ morla_fake_pgid + 1 }}:{{ morla_fake_pgid + 1 }}:{{ morla_subgid_size - morla_fake_pgid }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
