---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for wordle
morla_wordle_enabled: true

# Name
morla_wordle_long_name: Wordle
morla_wordle_short_name: wordle

morla_wordle_public_url: '{{ morla_wordle_short_name }}.{{ morla_public_url }}'

# filesystem dir for configs
morla_wordle_config_dir: '{{ morla_config_dir }}/Wordle'
morla_wordle_git_dir: '{{ role_path }}/files/wordle-git'

morla_wordle_git_repo: https://github.com/cwackerfuss/react-wordle.git

morla_wordle_container_name: '{{ morla_user_username }}-{{morla_wordle_short_name}}'
morla_wordle_container_image_base: '{{ morla_wordle_short_name }}'
morla_wordle_container_image_tag: prod
morla_wordle_container_image: '{{ morla_wordle_container_image_base }}:{{ morla_wordle_container_image_tag }}'
morla_wordle_container_extra_args: --target=prod

# Networking
morla_wordle_reverse_proxy_port: 32123
morla_wordle_exposed_proxy_port: '{{ morla_wordle_reverse_proxy_port }}'

# Networking/Firewall
morla_wordle_fw_ports:
    tcp:
        - '{{ morla_wordle_reverse_proxy_port }}'
    udp:

# Networking/Port Forwarding
morla_wordle_ports:
    - '{{ morla_wordle_reverse_proxy_port }}:8080'
