---
    - name: Check if Config dir exists
      stat:
          path: '{{ morla_jellyfin_config_dir }}'
      register: check_jellyfin_config_dir

    - name: Check if Cache dir exists
      stat:
          path: '{{ morla_jellyfin_cache_dir }}'
      register: check_jellyfin_cache_dir

    - name: Enable setsebool option to allow the use of the render device
      ansible.posix.seboolean:
          name: container_use_dri_devices
          state: true
          persistent: true
      become: true

