---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_jellyfin_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_jellyfin_config_dir.stat.exists

    - name: Create cache directory
      ansible.builtin.file:
          path: '{{ morla_jellyfin_cache_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_jellyfin_cache_dir.stat.exists

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_jellyfin_container_name }}'
          image: '{{ morla_jellyfin_container_image}}'
          network: morla-wireguard-network
          network_aliases: '{{ morla_jellyfin_short_name }}'
          ports: '{{ morla_jellyfin_ports }}'
          volumes: '{{ morla_jellyfin_volumes }}'
          label: '{{ morla_jellyfin_labels }}'
          # from getent group render | cut -d: -f3
          group_add: 997
          # requires setsebool container_use_devices=true 
          device: "/dev/dri/renderD128:/dev/dri/renderD128"
          env:
              TZ: '{{ morla_tz }}'
              JELLYFIN_PublishedServerUrl: 'http://{{ morla_jellyfin_public_url }}'
          state: started
          generate_systemd:
              path: '{{ morla_home_config_systemd_dir }}'
              restart_policy: always
              names: true
              container_prefix: '{{ morla_systemd_service_prefix }}'
