---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_jellyseerr_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_jellyseerr_config_dir.stat.exists

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_jellyseerr_container_name }}'
          image: '{{ morla_jellyseerr_container_image}}'
          network: morla-wireguard-network
          network_aliases: '{{ morla_jellyseerr_short_name }}'
          ports: '{{ morla_jellyseerr_ports }}'
          volumes: '{{ morla_jellyseerr_volumes }}'
          label: '{{ morla_jellyseerr_labels }}'
          env:
              TZ: '{{ morla_tz }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
