- name: Open ports for Prowlarr
  become: yes
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  loop: "{{ morla_prowlarr_fw_ports.tcp }}"
