# roles/prowlarr/tasks/main.yml

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/pull_prowlarr.yml"
  when: "morla_prowlarr_enabled | bool"
  tags:
    - setup-all
    - setup-prowlarr

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/destroy_prowlarr.yml"
  when: "morla_prowlarr_enabled | bool"
  tags:
    - never
    - destroy-all
    - destroy-prowlarr

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_prowlarr.yml"
  when: "morla_prowlarr_enabled | bool"
  tags:
    - setup-all
    - setup-prowlarr
