---
# roles/flaresolverr/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      when: morla_flaresolverr_enabled | bool
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      when: morla_flaresolverr_enabled | bool
      tags:
          - always
          - setup-all
          - setup-flaresolverr

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_flaresolverr.yml'
      when: morla_flaresolverr_enabled | bool
      tags:
          - setup-all
          - setup-flaresolverr

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_flaresolverr.yml'
      when: morla_flaresolverr_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-flaresolverr

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_flaresolverr.yml'
      when: morla_flaresolverr_enabled | bool
      tags:
          - setup-all
          - setup-flaresolverr
