---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_piwigo_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_piwigo_config_dir.stat.exists

    - name: Create DB config directory
      ansible.builtin.file:
          path: '{{ morla_piwigo_db_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_piwigo_db_config_dir.stat.exists

    - name: Create pod
      containers.podman.podman_pod:
          name: '{{ morla_piwigo_pod_name }}'
          network: morla-wireguard-network
          ports: '{{ morla_piwigo_ports }}'
          label: '{{ morla_piwigo_labels }}'
          uidmap:
              - '{{ morla_fake_puid }}:0:1'
              - 0:1:{{ morla_fake_puid }}
              - '{{ morla_fake_puid + 1 }}:{{ morla_fake_puid + 1 }}:{{ morla_subuid_size - morla_fake_puid }}'
          gidmap:
              - '{{ morla_fake_pgid }}:0:1'
              - 0:1:{{ morla_fake_pgid }}
              - '{{ morla_fake_pgid + 1 }}:{{ morla_fake_pgid + 1 }}:{{ morla_subgid_size - morla_fake_pgid }}'
          state: quadlet
          quadlet_options:
            - |
              [Install]
              WantedBy=default.target

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_piwigo_container_name }}'
          image: '{{ morla_piwigo_container_image}}'
          pod: '{{ morla_piwigo_pod_name }}'
          volumes: '{{ morla_piwigo_volumes }}'
          env:
              PUID: '{{ morla_fake_puid }}'
              PGID: '{{ morla_fake_pgid }}'
              TZ: '{{ morla_tz }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target

    - name: Create Database
      containers.podman.podman_container:
          name: '{{ morla_piwigo_db_container_name }}'
          image: '{{ morla_piwigo_db_container_image }}'
          pod: '{{ morla_piwigo_pod_name }}'
          network: container:morla-piwigo
          volumes: '{{ morla_piwigo_db_volumes }}'
          env:
              PUID: '{{ morla_fake_puid }}'
              PGID: '{{ morla_fake_pgid }}'
              TZ: '{{ morla_tz }}'
              MYSQL_USER: '{{ morla_piwigo_db_env_mysql_user }}'
              MYSQL_PASSWORD: '{{ morla_piwigo_db_env_mysql_password }}'
              MYSQL_DATABASE: '{{ morla_piwigo_db_env_mysql_database }}'
              MYSQL_RANDOM_ROOT_PASSWORD: '{{ morla_piwigo_db_env_mysql_random_root_password }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
