---
    - name: Get All Firewall Services
      become: yes
      ansible.builtin.command: "firewall-cmd --list-services --zone=home"
      register: firewalld_command_output
      changed_when: false

    - name: Put All Services Into a List
      set_fact:
        all_firewalld_services: '{{ firewalld_command_output.stdout | split }}'

    - name: Filter Out Default Firewall Services
      set_fact:
        all_container_firewalld_services: '{{ all_firewalld_services | difference(morla_default_firewalld_services) }}'

    - name: Get a List from Enabled Firewall Services Dict
      set_fact:
        enabled_container_firewalld_services_list: '{{ enabled_container_firewalld_services_list | default([]) + [item.name] }}'
      loop: '{{ morla_firewall_services }}'

    - name: Get All Enabled Firewall Services
      set_fact:
        enabled_container_firewalld_services: "{{ enabled_container_firewalld_services_list | map('regex_replace', '^', 'container-morla-') | list }}"

    - name: Filter Out Enabled Container Firewall Services
      set_fact:
        disabled_container_firewalld_services: '{{ all_container_firewalld_services | difference(enabled_container_firewalld_services) }}'

    - name: Close All Disabled Container Firewall Services
      become: yes
      ansible.posix.firewalld:
        service: '{{ item }}'
        permanent: yes
        zone: home
        state: disabled
        immediate: true
      loop: '{{ disabled_container_firewalld_services }}'

    - name: Ensure Default Firewall Services Are Enabled
      become: yes
      ansible.posix.firewalld:
        service: '{{ item }}'
        permanent: yes
        zone: home
        state: enabled
        immediate: true
      loop: '{{ morla_default_firewalld_services }}'

    - name: Ensure Enable Container Firewall Service Are Active
      become: yes
      ansible.posix.firewalld:
        service: '{{ item }}'
        permanent: yes
        zone: home
        state: enabled
        immediate: true
      loop: '{{ enabled_container_firewalld_services }}'
