---
    - name: Get All Firewall Services
      become: yes
      ansible.builtin.command: "firewall-cmd --list-services --zone=home"
      register: all_firewall_services

    - name: Close All Firewall Services
      become: yes
      ansible.posix.firewalld:
        service: '{{ item }}'
        permanent: yes
        zone: home
        state: disabled
        immediate: true
      loop: "{{ all_firewall_services.stdout | split }}"

    - name: Enable Default Firewall Services
      become: yes
      ansible.posix.firewalld:
        service: '{{ item }}'
        permanent: yes
        zone: home
        state: enabled
        immediate: true
      loop:
        - cockpit
        - dhcpv6-client
        - mdns
        - samba-client
        - ssh


    - name: Enable Container Firewall Service
      become: yes
      ansible.posix.firewalld:
        service: container-morla-{{ item.name }}
        permanent: yes
        zone: home
        state: enabled
        immediate: true
      loop: '{{ morla_firewall_services }}'
