---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for pyload
morla_pyload_enabled: false

morla_pyload_flag_public: false
morla_pyload_flag_autostart: true
morla_pyload_flag_wireguard: true
morla_pyload_flag_firewall: true # replace with if port list non empty

# Name
morla_pyload_long_name: Pyload
morla_pyload_short_name: pyload

morla_pyload_container_short_name: '{{ morla_pyload_short_name }}'
morla_pyload_container_name: '{{ morla_user_username }}-{{ morla_pyload_container_short_name }}'
morla_pyload_public_url: '{{ morla_pyload_short_name }}.{{ morla_public_url }}'

morla_pyload_container_image_base: lscr.io/linuxserver/pyload
morla_pyload_container_image_tag: latest
morla_pyload_container_image: '{{ morla_pyload_container_image_base }}:{{ morla_pyload_container_image_tag }}'

# Networking
morla_pyload_reverse_proxy_port: '8000'
morla_pyload_exposed_proxy_port: '{{ morla_pyload_reverse_proxy_port }}'

# Networking/Firewall
morla_pyload_fw_ports:
    tcp:
        - '{{ morla_pyload_reverse_proxy_port }}'
        - '7227'
    udp:

# Networking/Port Forwarding
morla_pyload_ports:
    - '{{ morla_pyload_reverse_proxy_port }}:{{ morla_pyload_exposed_proxy_port }}'
    - '{{ morla_pyload_fw_ports.tcp[1] }}:{{ morla_pyload_fw_ports.tcp[1] }}'

# Storage/Host
morla_pyload_config_dir: '{{ morla_config_dir }}/{{ morla_pyload_long_name }}'
morla_pyload_downloads_dir: '{{ morla_pyload_dir }}'

# Storage/Mount
morla_pyload_volumes:
    - '{{ morla_pyload_config_dir }}:/config:Z'
    - '{{ morla_pyload_downloads_dir }}:/downloads:z'

# Labels/Traefik
morla_pyload_labels:
    traefik.enable: '{{ morla_pyload_flag_public }}'
    traefik.http.services.pyload.loadbalancer.server.port: '{{ morla_pyload_exposed_proxy_port }}'
    traefik.http.routers.pyload.tls: true
    traefik.http.routers.pyload.rule: Host(`{{ morla_pyload_public_url }}`)
    traefik.http.routers.pyload.entrypoints: websecure
    traefik.http.routers.pyload.tls.certresolver: myresolver
    traefik.http.routers.pyload.tls.domains: '{{ morla_pyload_public_url }}'
    traefik.http.routers.pyload.middlewares: wireguard-ipwhitelist@file
