---
morla_qbittorrent_enabled: true
morla_qbittorrent_become: true

morla_qbittorrent_flag_public: false
morla_qbittorrent_flag_autostart: true
morla_qbittorrent_flag_wireguard: true
morla_qbittorrent_flag_firewall: true # replace with if port list non empty

morla_qbittorrent_long_name: Qbittorrent
morla_qbittorrent_short_name: qbittorrent

morla_qbittorrent_container_short_name: '{{ morla_qbittorrent_short_name }}'
morla_qbittorrent_container_name: '{{ morla_user_username }}-{{ morla_qbittorrent_container_short_name }}'

morla_qbittorrent_public_url: '{{ morla_qbittorrent_short_name }}.{{ morla_public_url }}'

# filesystem dir for configs
morla_qbittorrent_config_dir: '{{ morla_config_dir }}/{{ morla_qbittorrent_long_name }}'
morla_qbittorrent_torrents_dir: '{{ morla_torrents_dir }}'

morla_qbittorrent_container_image_base: lscr.io/linuxserver/qbittorrent
morla_qbittorrent_container_image_tag: latest
morla_qbittorrent_container_image: '{{ morla_qbittorrent_container_image_base }}:{{ morla_radarr_container_image_tag }}'

morla_qbittorrent_env_webui_port: 9092
  # morla_qbittorrent_web_home: "/flood-for-qbittorrent/"

# used inside container config
morla_qbittorrent_internal_ip: 172.20.0.92
morla_qbittorrent_reverse_proxy_port: '{{ morla_qbittorrent_env_webui_port }}'

morla_qbittorrent_fw_ports:
    tcp:
        - '{{ morla_qbittorrent_reverse_proxy_port }}'
        - '6881'
    udp:
        - '6881'

morla_qbittorrent_ports:
    - '{{ morla_qbittorrent_reverse_proxy_port }}:{{ morla_qbittorrent_reverse_proxy_port }}'
    - '{{ morla_qbittorrent_fw_ports.tcp[1] }}:{{ morla_qbittorrent_fw_ports.tcp[1] }}'
    - '{{ morla_qbittorrent_fw_ports.udp[0] }}:{{ morla_qbittorrent_fw_ports.udp[0] }}/udp'

morla_qbittorrent_volumes:
    - '{{ morla_qbittorrent_config_dir }}:/config:Z'
    - '{{ morla_qbittorrent_torrents_dir }}:/data/torrents'
