---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for qbittorrent
morla_qbittorrent_enabled: false

morla_qbittorrent_flag_public: false
morla_qbittorrent_flag_autostart: true
morla_qbittorrent_flag_wireguard: true
morla_qbittorrent_flag_firewall: true # replace with if port list non empty

# Name
morla_qbittorrent_long_name: Qbittorrent
morla_qbittorrent_short_name: qbittorrent

morla_qbittorrent_container_short_name: '{{ morla_qbittorrent_short_name }}'
morla_qbittorrent_container_name: '{{ morla_user_username }}-{{ morla_qbittorrent_container_short_name }}'
morla_qbittorrent_public_url: '{{ morla_qbittorrent_short_name }}.{{ morla_public_url }}'

morla_qbittorrent_container_image_base: lscr.io/linuxserver/qbittorrent
morla_qbittorrent_container_image_tag: latest
morla_qbittorrent_container_image: '{{ morla_qbittorrent_container_image_base }}:{{ morla_qbittorrent_container_image_tag }}'

# Networking
morla_qbittorrent_reverse_proxy_port: '9092'
morla_qbittorrent_exposed_proxy_port: '{{ morla_qbittorrent_reverse_proxy_port }}'

# Networking/Firewall
morla_qbittorrent_fw_ports:
    tcp:
        - '{{ morla_qbittorrent_reverse_proxy_port }}'
        - '6881'
    udp:
        - '6881'

# Networking/Port Forwarding
morla_qbittorrent_ports:
    - '{{ morla_qbittorrent_reverse_proxy_port }}:{{ morla_qbittorrent_exposed_proxy_port }}'
    - '{{ morla_qbittorrent_fw_ports.tcp[1] }}:{{ morla_qbittorrent_fw_ports.tcp[1] }}'
    - '{{ morla_qbittorrent_fw_ports.udp[0] }}:{{ morla_qbittorrent_fw_ports.udp[0] }}/udp'

# Storage/Host
morla_qbittorrent_volumes:
    - '{{ morla_qbittorrent_config_dir }}:/config:Z'
    - '{{ morla_qbittorrent_torrents_dir }}:/data/torrents'

# Storage/Mount
morla_qbittorrent_config_dir: '{{ morla_config_dir }}/{{ morla_qbittorrent_long_name }}'
morla_qbittorrent_torrents_dir: '{{ morla_torrents_dir }}'

# Environment
morla_qbittorrent_env_webui_port: '{{ morla_qbittorrent_exposed_proxy_port }}'

# Labels/Traefik
morla_qbittorrent_labels:
    traefik.enable: '{{ morla_qbittorrent_flag_public }}'
    traefik.http.services.qbittorrent.loadbalancer.server.port: '{{ morla_qbittorrent_exposed_proxy_port }}'
    traefik.http.routers.qbittorrent.tls: true
    traefik.http.routers.qbittorrent.rule: Host(`{{ morla_qbittorrent_public_url }}`)
    traefik.http.routers.qbittorrent.entrypoints: websecure
    traefik.http.routers.qbittorrent.tls.certresolver: myresolver
    traefik.http.routers.qbittorrent.tls.domains: '{{ morla_qbittorrent_public_url }}'
