---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for traefik

morla_traefik_flag_public: false
morla_traefik_flag_autostart: true
morla_traefik_flag_wireguard: false
morla_traefik_flag_firewall: true # replace with if port list non empty

# Name
morla_traefik_long_name: Traefik
morla_traefik_short_name: traefik

morla_traefik_container_short_name: traefik
morla_traefik_container_name: '{{ morla_user_username }}-{{ morla_traefik_container_short_name }}'

morla_traefik_container_image_base: docker.io/library/traefik
morla_traefik_container_image_tag: v3.0
morla_traefik_container_image: '{{ morla_traefik_container_image_base }}:{{ morla_traefik_container_image_tag }}'

# Network
morla_traefik_http_port: '1680'
morla_traefik_https_port: '1643'
morla_traefik_dashboard_port: '8080'

# Network/Firewall
morla_traefik_fw_ports:
    tcp:
        - '80'
        - '443'
        - '{{ morla_traefik_http_port }}'
        - '{{ morla_traefik_https_port }}'
        - '{{ morla_traefik_dashboard_port }}'
    udp:

# Network/Port Forwarding
morla_traefik_ports:
    - '{{ morla_traefik_http_port }}:80'
    - '{{ morla_traefik_https_port }}:443'
    # - '{{ morla_tailscale_ip }}:80:80'
    # - '{{ morla_tailscale_ip }}:443:443'
    - '{{ morla_traefik_dashboard_port }}:8080'

# Storage/Host
morla_traefik_config_dir: '{{ morla_config_dir }}/{{ morla_traefik_long_name}}'
morla_traefik_letsencrypt_dir: '{{ morla_config_dir }}/{{ morla_traefik_long_name}}Letsencrypt'
morla_traefik_cloudflared_config_dir: '{{ morla_config_dir }}/{{ morla_traefik_long_name }}CloudflaredCerts'

# Storage/Mount
morla_traefik_volumes:
    # TOML Configuration with global options
    # - '{{ morla_traefik_config_dir }}/traefik.toml:/traefik.toml:Z'
    # Configuration for the file provider (needed for host networking and default TLS Options)
    # - '{{ morla_traefik_config_dir }}/traefik-provider.toml:/traefik-provider.toml:Z'
    # LetsEncrypt ACME Configuration
    # - '{{ morla_traefik_config_dir }}/acme.json:/acme.json:Z'
    # Log File (optional)
    # - '{{ morla_traefik_config_dir }}/traefik.log:/traefik.log:Z'
    - '{{ morla_traefik_letsencrypt_dir }}:/letsencrypt:Z'
    - /run/user/{{ morla_user_puid }}/podman/podman.sock:/var/run/docker.sock:z,ro

# Command
morla_traefik_command:
    - --log.level=DEBUG
    - --api.insecure=true
    - --api.dashboard=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80/tcp
    - --entrypoints.websecure.address=:443/tcp
    - --entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,192.168.1.166,172.20.0.0/24,172.120.0.0/24
    - --certificatesresolvers.myresolver.acme.dnschallenge=true
    - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
    - --certificatesresolvers.myresolver.acme.email={{ morla_letsencrypt_email }}
    - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    - --accesslog=true
    - --accesslog.filepath=/mnt/logs/access.log
    - --accesslog.bufferingsize=100

morla_traefik_labels:
    traefik.enable: true
    traefik.http.routers.traefik.rule: Host(`traefik.{{ morla_domain }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    traefik.http.routers.traefik.service: api@internal
    traefik.http.routers.traefik.entrypoints: websecure
    traefik.http.routers.traefik.tls.certresolver: myresolver

# Sec Opt
morla_traefik_security_opt:
    - label=disable

# PUID/PGID
morla_traefik_puid: 101
morla_traefik_pgid: 101

morla_traefik_env_cloudflare_dns_api_token: '{{ morla_traefik_cloudflare_dns_api_token }}'

