- name: Close TCP ports for Filebrowser
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: disabled
    immediate: true
  loop: "{{ morla_filebrowser_fw_ports.tcp }}"

- name: Close UDP ports for Filebrowser
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: disabled
    immediate: true
  loop: "{{ morla_filebrowser_fw_ports.udp }}"

