- name: Create container
  containers.podman.podman_container:
    name: "{{ morla_filebrowser_container_name }}"
    image: "{{ morla_filebrowser_container_image}}"
    volumes: "{{ morla_filebrowser_volumes }}"
    #ports: "{{ morla_filebrowser_ports }}"
    env:
      PUID: "{{ morla_root_puid }}"
      PGID: "{{ morla_root_pgid }}"
      TZ: "{{ morla_tz }}"
    state: started
    pod: morla-wireguard-pod
    restart_policy: unless-stopped
    generate_systemd:
      path: "{{ morla_home_config_systemd_dir }}"
      restart_policy: always
      names: true
      container_prefix: "{{ morla_systemd_service_prefix }}"
