---
morla_photoprism_enabled: true

morla_photoprism_flag_public: true
morla_photoprism_flag_autostart: true
morla_photoprism_flag_wireguard: true
morla_photoprism_flag_firewall: true # replace with if port list non empty

morla_photoprism_long_name: Photoprism
morla_photoprism_short_name: photoprism

morla_photoprism_container_short_name: '{{ morla_photoprism_short_name }}'
morla_photoprism_container_name: '{{ morla_user_username }}-{{ morla_photoprism_container_short_name }}'

morla_photoprism_public_url: '{{ morla_photoprism_short_name }}.{{ morla_public_url }}'

# filesystem dir for configs
morla_photoprism_config_dir: '{{ morla_config_dir }}/{{ morla_photoprism_long_name }}'
morla_photoprism_originals_dir: '{{ morla_media_dir }}/pictures/photoprism/originals'
morla_photoprism_imported_dir: '{{ morla_media_dir }}/pictures/photoprism/imported'

morla_photoprism_container_image_base: docker.io/photoprism/photoprism
morla_photoprism_container_image_tag: latest
morla_photoprism_container_image: '{{ morla_photoprism_container_image_base }}:{{ morla_radarr_container_image_tag }}'

# used inside container config
morla_photoprism_reverse_proxy_port: '2342'
morla_photoprism_internal_ip: 172.20.0.23

morla_photoprism_fw_ports:
    tcp:
        - '{{ morla_photoprism_reverse_proxy_port }}'
    udp:


morla_photoprism_ports:
    - '{{ morla_photoprism_reverse_proxy_port }}:{{ morla_photoprism_reverse_proxy_port}}'

morla_photoprism_volumes:
    - '{{ morla_photoprism_config_dir }}:/photoprism/storage:Z'
    - '{{ morla_photoprism_originals_dir }}:/photoprism/originals:z'
    - '{{ morla_photoprism_imported_dir }}:/photoprism/imported:z'
