---
    - name: Check if Git Wordle exist
      stat:
          path: '{{ morla_wordle_git_dir }}'
      register: check_wordle_git_dir

    - name: Clone Wordle if Git dir does not exsist
      ansible.builtin.git:
          repo: '{{ morla_wordle_git_repo }}'
          dest: '{{ morla_wordle_git_dir }}'
          update: yes
  # when: not check_wordle_git_dir.stat.exists


# Impossible to build automatically at the moment
# Build manually :/
#
# - name: Build wordle
#   containers.podman.podman_image:
#     name: "{{ morla_wordle_container_image}}"
#     path: "{{ morla_wordle_git_dir }}/docker"
#     build:
#       annotation:
#         app: "{{ morla_wordle_container_name }}"
#         info: Wordle in React
#       extra_args: "{{ morla_wordle_container_extra_args }}"
