---
- name: Add Filebrowser to the list of public domains
  ansible.builtin.set_fact:
    morla_public_domains: "{{ morla_public_domains + [ morla_wordle_short_name ] }}"

- name: Add Container to the list of autostart containers
  ansible.builtin.set_fact:
    morla_systemd_autostart_containers: "{{ morla_systemd_autostart_containers + [ morla_wordle_container_name ] }}"
