# roles/wordle/tasks/main.yaml


- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yaml"
  tags:
    - always

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/build_wordle.yaml"
  when: "morla_wordle_enabled | bool"
  tags:
    - setup-all
    - setup-wordle

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/destroy_wordle.yaml"
  when: "morla_wordle_enabled | bool"
  tags:
    - never
    - destroy-all
    - destroy-wordle

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_wordle.yaml"
  when: "morla_wordle_enabled | bool"
  tags:
    - setup-all
    - setup-wordle

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/fw_close_wordle.yaml"
  when: "morla_wordle_enabled | bool"
  tags:
    - never
    - destroy-all
    - destroy-wordle
    - fw-down-all
    - fw-down-wordle

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/fw_open_wordle.yaml"
  when: "morla_wordle_enabled | bool"
  tags:
    - fw-up-all
    - fw-up-wordle
    - setup-all
    - setup-wordle

