# syntax=docker/dockerfile:1           
                                       
FROM python:3.8-slim-buster            
                                       
RUN pip3 install --upgrade pip         
                                       
COPY . /app 
                                       
RUN pip3 install -r /app/requirements.txt   
                                       
WORKDIR /app

CMD [ "python3", "/app/gandi_ddns.py" ]
