---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for sonarr
morla_sonarr_enabled: false
morla_sonarr_become: true

morla_sonarr_flag_public: true
morla_sonarr_flag_autostart: true
morla_sonarr_flag_wireguard: true
morla_sonarr_flag_firewall: true # replace with if port list non empty

# Name
morla_sonarr_long_name: Sonarr
morla_sonarr_short_name: sonarr

morla_sonarr_container_short_name: '{{ morla_sonarr_short_name }}'
morla_sonarr_container_name: '{{ morla_user_username }}-{{ morla_sonarr_container_short_name }}'
morla_sonarr_public_url: '{{ morla_sonarr_short_name }}.{{ morla_public_url }}'
morla_sonarr_tailscale_url: '{{ morla_sonarr_short_name }}.{{ morla_tailscale_url }}'

morla_sonarr_container_image_base: ghcr.io/hotio/sonarr
morla_sonarr_container_image_tag: latest
morla_sonarr_container_image: '{{ morla_sonarr_container_image_base }}:{{ morla_sonarr_container_image_tag }}'

# Networking
morla_sonarr_reverse_proxy_port: '8989'
morla_sonarr_exposed_proxy_port: '{{ morla_sonarr_reverse_proxy_port }}'

# Networking/Firewall
morla_sonarr_fw_ports:
    tcp:
        - '{{ morla_sonarr_reverse_proxy_port }}'
    udp:

# Networking/Port Forwarding
morla_sonarr_ports:
    - '{{ morla_sonarr_reverse_proxy_port }}:{{ morla_sonarr_exposed_proxy_port }}'

# Storage/Host
morla_sonarr_config_dir: '{{ morla_config_dir }}/{{ morla_sonarr_long_name }}'
morla_sonarr_data_dir: '{{ morla_media_dir }}'

# Storage/Mount
morla_sonarr_volumes:
    - '{{ morla_sonarr_config_dir }}:/config:Z'
    - '{{ morla_sonarr_data_dir }}:/data/media:z'
    - '{{ morla_torrents_dir }}:/data/torrents:z'

# Labels/Traefik
morla_sonarr_labels:
    traefik.enable: '{{ morla_sonarr_flag_public }}'
    traefik.http.services.sonarr.loadbalancer.server.port: '{{ morla_sonarr_exposed_proxy_port }}'
    traefik.http.routers.sonarr.tls: true
    traefik.http.routers.sonarr.rule: Host(`{{ morla_sonarr_tailscale_url }}`)
    traefik.http.routers.sonarr.entrypoints: websecure
    traefik.http.routers.sonarr.tls.certresolver: myresolver
    traefik.http.routers.sonarr.tls.domains: '{{ morla_sonarr_tailscale_url }}'
