---
morla_sonarr_enabled: true
morla_sonarr_become: true

morla_sonarr_flag_public: false
morla_sonarr_flag_autostart: true
morla_sonarr_flag_wireguard: true
morla_sonarr_flag_firewall: true # replace with if port list non empty

morla_sonarr_long_name: Sonarr
morla_sonarr_short_name: sonarr

morla_sonarr_container_short_name: '{{ morla_sonarr_short_name }}'
morla_sonarr_container_name: '{{ morla_user_username }}-{{ morla_sonarr_container_short_name }}'

morla_sonarr_public_url: '{{ morla_sonarr_short_name }}.{{ morla_public_url }}'

# filesystem dir for configs
morla_sonarr_config_dir: '{{ morla_config_dir }}/{{ morla_sonarr_long_name }}'
morla_sonarr_data_dir: '{{ morla_data_dir }}'

morla_sonarr_container_image_base: cr.hotio.dev/hotio/sonarr
morla_sonarr_container_image_tag: latest
morla_sonarr_container_image: '{{ morla_sonarr_container_image_base }}:{{ morla_sonarr_container_image_tag }}'

# used inside container config
morla_sonarr_volumes:
    - '{{ morla_sonarr_config_dir }}:/config:Z'
    - '{{ morla_sonarr_data_dir }}:/data:z'

morla_sonarr_internal_ip: 172.20.0.89

morla_sonarr_reverse_proxy_port: '8989'

morla_sonarr_fw_ports:
    tcp:
        - '{{ morla_sonarr_reverse_proxy_port }}'

morla_sonarr_ports:
    - '{{ morla_sonarr_reverse_proxy_port }}:{{ morla_sonarr_reverse_proxy_port }}'
