- name: Install cronjob to install letsencrypt certs twice a day
  ansible.builtin.cron:
    name: "renew certs for {{ item }}.{{ morla_public_url }}"
    minute: "0"
    hour: "10,22"
    job:
      "/usr/bin/podman run --rm --name certbot -v {{ morla_letsencrypt_dir }}:/etc/letsencrypt:z {{ morla_certbot_gandi_short_name }} certbot certonly --authenticator dns-gandi --dns-gandi-credentials /etc/letsencrypt/gandi/gandi.ini --agree-tos --non-interactive -m {{ morla_letsencrypt_email }} -d {{ item }}.{{ morla_public_url }}"
  loop: "{{ morla_public_domains }}"
  register: check_cron_install

- name: Restart service cron, also issue daemon-reload
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: crond
  when: check_cron_install.changed
