---
- name: Check if certificate exists
  stat:
    path: "{{ morla_letsencrypt_dir }}/live/{{ item }}.{{ morla_public_url }}"
  register: check_letsencrypt_dir
  loop: "{{ morla_public_domains }}"

    # check if all are created and don't copy files to nginx

- name: Run Certbot
  ansible.builtin.shell: |
    /usr/bin/podman run --rm \
    --name certbot \
    -v /home/morla/Config/Letsencrypt/etc/letsencrypt:/etc/letsencrypt:Z \
    certbot-gandi certbot certonly \
    --authenticator dns-gandi \
    --dns-gandi-credentials /etc/letsencrypt/gandi/gandi.ini \
    --agree-tos \
    --non-interactive \
    -m {{ morla_letsencrypt_email }} \
    -d {{ item.item }}.{{ morla_public_url }}
  loop: "{{ check_letsencrypt_dir.results }}"
  register: new_certificate
  when: item.stat.exists == False
