---
morla_nginx_long_name: Nginx

morla_nginx_flag_public: false
morla_nginx_flag_autostart: true
morla_nginx_flag_wireguard: false
morla_nginx_flag_firewall: true # replace with if port list non empty

morla_nginx_short_name: nginx

morla_nginx_container_short_name: nginx
morla_nginx_container_name: '{{ morla_user_username }}-{{ morla_nginx_container_short_name }}'

morla_nginx_config_dir: '{{ morla_config_dir }}/{{ morla_nginx_long_name}}'
morla_nginx_site_confs: '{{ morla_nginx_config_dir }}/nginx/site-confs/'
morla_nginx_etc_letsencrypt: '{{ morla_nginx_config_dir }}/etc/letsencrypt'
morla_nginx_etc_nginx_sites_enabled: '{{ morla_nginx_etc_nginx }}/sites-enabled'

morla_nginx_container_image_base: lscr.io/linuxserver/nginx
morla_nginx_container_image_tag: latest
morla_nginx_container_image: '{{ morla_nginx_container_image_base }}:{{ morla_nginx_container_image_tag }}'

morla_nginx_puid: 101
morla_nginx_pgid: 101

morla_nginx_http_port: '16680'
morla_nginx_https_port: '16443'

morla_nginx_fw_ports:
    tcp:
        - '{{ morla_nginx_http_port }}'
        - '{{ morla_nginx_https_port}}'
    udp:

morla_nginx_ports:
    - 16680:80
    - 16443:443

morla_nginx_volumes:
    - '{{ morla_nginx_config_dir }}:/config:Z'
    - '{{ morla_letsencrypt_dir }}:/certs:z'
