morla_wireguard_enabled: true

morla_wireguard_flag_public: false
morla_wireguard_flag_autostart: true
morla_wireguard_flag_wireguard: false

morla_wireguard_long_name: "Wireguard"
morla_wireguard_short_name: wireguard

morla_wireguard_pod_name: "morla-wireguard-pod"
morla_wireguard_network_name: "morla-wireguard-network"

morla_wireguard_container_short_name: "{{ morla_wireguard_short_name }}"
morla_wireguard_container_name: "{{ morla_user_username }}-{{ morla_wireguard_container_short_name }}"

morla_wireguard_public_url: "{{ morla_wireguard_short_name }}.{{ morla_public_url }}"

# filesystem dir for configs
morla_wireguard_config_dir: "{{ morla_config_dir }}/{{ morla_wireguard_long_name }}"

morla_wireguard_container_image_base: "lscr.io/linuxserver/wireguard"
morla_wireguard_container_image_tag: "latest"
morla_wireguard_container_image: "{{ morla_wireguard_container_image_base }}:{{ morla_wireguard_container_image_tag }}"

morla_wireguard_cap_add: 
  - NET_ADMIN
  - NET_RAW
  - SYS_MODULE

morla_wireguard_privileged: true
morla_wireguard_env_serverurl: "89.103.120.9"
morla_wireguard_env_peers: "nik_phone,nik_pc_work,nik_pc_home,nik_pc_gaming,leo_phone,leo_pc_home"
# used inside container config
morla_wireguard_external_server_port: "12882"
morla_wireguard_reverse_proxy_port: "51820"

morla_wireguard_fw_ports:
  tcp:
  udp:
    - "{{ morla_wireguard_external_server_port }}"

morla_wireguard_ports:
  - "{{ morla_wireguard_fw_ports.udp[0] }}:{{ morla_wireguard_reverse_proxy_port }}/udp"

morla_wireguard_volumes:
  - "{{ morla_wireguard_config_dir }}:/config:Z"
  - "/lib/modules:/lib/modules"
