---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for readarr
morla_readarr_enabled: false
morla_readarr_become: true

morla_readarr_flag_public: false
morla_readarr_flag_autostart: true
morla_readarr_flag_wireguard: true
morla_readarr_flag_firewall: true # replace with if port list non empty

# Name
morla_readarr_long_name: Readarr
morla_readarr_short_name: readarr

morla_readarr_container_short_name: '{{ morla_readarr_short_name }}'
morla_readarr_container_name: '{{ morla_user_username }}-{{ morla_readarr_container_short_name }}'
morla_readarr_public_url: '{{ morla_readarr_short_name }}.{{ morla_public_url }}'

morla_readarr_container_image_base: ghcr.io/hotio/readarr
morla_readarr_container_image_tag: latest
morla_readarr_container_image: '{{ morla_readarr_container_image_base }}:{{ morla_readarr_container_image_tag }}'

# Networking
morla_readarr_reverse_proxy_port: '8787'
morla_readarr_exposed_proxy_port: '{{ morla_readarr_reverse_proxy_port }}'

# Networking/Firewall
morla_readarr_fw_ports:
    tcp:
        - '{{ morla_readarr_reverse_proxy_port }}'
    udp:

# Networking/Port Forwarding
morla_readarr_ports:
    - '{{ morla_readarr_reverse_proxy_port }}:{{ morla_readarr_exposed_proxy_port }}'

# Storage/Host
morla_readarr_config_dir: '{{ morla_config_dir }}/{{ morla_readarr_long_name }}'
morla_readarr_data_dir: '{{ morla_media_dir }}'

# Storage/Mount
morla_readarr_volumes:
    - '{{ morla_readarr_config_dir }}:/config:Z'
    - '{{ morla_readarr_data_dir }}:/data/media:z'
    - '{{ morla_torrents_dir }}:/data/torrents:z'

# Labels/Traefik
morla_readarr_labels:
    traefik.enable: '{{ morla_readarr_flag_public }}'
    traefik.http.services.readarr.loadbalancer.server.port: '{{ morla_readarr_exposed_proxy_port }}'
    traefik.http.routers.readarr.tls: true
    traefik.http.routers.readarr.rule: Host(`{{ morla_readarr_public_url }}`)
    traefik.http.routers.readarr.entrypoints: websecure
    traefik.http.routers.readarr.tls.certresolver: myresolver
    traefik.http.routers.readarr.tls.domains: '{{ morla_readarr_public_url }}'
