---
# roles/nginx/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      tags:
          - setup-all
          - setup-nginx

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_nginx.yml'
      tags:
          - setup-all
          - setup-nginx

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_nginx.yml'
      tags:
          - never
          - destroy-all
          - destroy-nginx

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_nginx.yml'
      tags:
          - setup-all
          - setup-nginx

    - ansible.builtin.import_tasks: '{{ role_path }}/templates/main.yml'
      tags:
          - setup-all
          - setup-nginx
