- name: Create container
  containers.podman.podman_container:
    name: "{{ morla_nginx_container_name }}"
    image: "{{ morla_nginx_container_image}}"
    volumes: "{{ morla_nginx_volumes }}"
    ports: "{{ morla_nginx_ports }}"
    env:
      PUID: "{{ morla_user_puid }}"
      PGID: "{{ morla_user_pgid }}"
      TZ: "{{ morla_tz }}"
    state: started
    restart_policy: unless-stopped
    generate_systemd:
      path: "{{ morla_home_config_systemd_dir }}"
      restart_policy: always
      names: true
      container_prefix: "{{ morla_systemd_service_prefix }}" 
