morla_prowlarr_enabled: true
morla_prowlarr_become: true

morla_prowlarr_flag_public: false
morla_prowlarr_flag_autostart: true
morla_prowlarr_flag_wireguard: true
morla_prowlarr_flag_firewall: true # replace with if port list non empty

morla_prowlarr_long_name: "Prowlarr"
morla_prowlarr_short_name: prowlarr

morla_prowlarr_container_short_name: "{{ morla_prowlarr_short_name }}"
morla_prowlarr_container_name: "{{ morla_user_username }}-{{ morla_prowlarr_container_short_name }}"

morla_prowlarr_public_url: "{{ morla_prowlarr_short_name }}.{{ morla_public_url }}"

# filesystem dir for configs
morla_prowlarr_config_dir: "{{ morla_config_dir }}/{{ morla_prowlarr_long_name }}"

morla_prowlarr_container_image_base: "cr.hotio.dev/hotio/prowlarr"
morla_prowlarr_container_image_tag: "latest"
morla_prowlarr_container_image: "{{ morla_prowlarr_container_image_base }}:{{ morla_prowlarr_container_image_tag }}"

# used inside container config
morla_prowlarr_volumes:
  - "{{ morla_prowlarr_config_dir }}:/config:Z"

morla_prowlarr_reverse_proxy_port: "9696"

morla_prowlarr_internal_ip: "172.20.0.96"
morla_prowlarr_fw_ports:
  tcp:
    - "{{ morla_prowlarr_reverse_proxy_port }}"

morla_prowlarr_ports:
  - "{{ morla_prowlarr_reverse_proxy_port }}:{{ morla_prowlarr_reverse_proxy_port }}"
