---
# SPDX-FileCopyrightText: Nicola Sella
#
# SPDX-License-Identifier: GPL-3.0-or-later

# configuration file for prowlarr
morla_prowlarr_enabled: true

morla_prowlarr_flag_public: false
morla_prowlarr_flag_autostart: true
morla_prowlarr_flag_wireguard: true
morla_prowlarr_flag_firewall: true # replace with if port list non empty

# Name
morla_prowlarr_long_name: Prowlarr
morla_prowlarr_short_name: prowlarr

morla_prowlarr_container_short_name: '{{ morla_prowlarr_short_name }}'
morla_prowlarr_container_name: '{{ morla_user_username }}-{{ morla_prowlarr_container_short_name }}'
morla_prowlarr_public_url: '{{ morla_prowlarr_short_name }}.{{ morla_public_url }}'

morla_prowlarr_container_image_base: cr.hotio.dev/hotio/prowlarr
morla_prowlarr_container_image_tag: latest
morla_prowlarr_container_image: '{{ morla_prowlarr_container_image_base }}:{{ morla_prowlarr_container_image_tag }}'

# Networking
morla_prowlarr_reverse_proxy_port: '9696'
morla_prowlarr_exposed_proxy_port: '{{ morla_prowlarr_reverse_proxy_port }}'
morla_prowlarr_internal_ip: 172.20.0.96

# Networking/Firewall
morla_prowlarr_fw_ports:
    tcp:
        - '{{ morla_prowlarr_reverse_proxy_port }}'
    udp:

# Networking/Port Forwarding
morla_prowlarr_ports:
    - '{{ morla_prowlarr_reverse_proxy_port }}:{{ morla_prowlarr_exposed_proxy_port }}'

# Storage/Host
morla_prowlarr_config_dir: '{{ morla_config_dir }}/{{ morla_prowlarr_long_name }}'

# Storage/Mount
morla_prowlarr_volumes:
    - '{{ morla_prowlarr_config_dir }}:/config:Z'

# Labels/Traefik
morla_prowlarr_labels:
    traefik.enable: '{{ morla_prowlarr_flag_public }}'
    traefik.http.services.prowlarr.loadbalancer.server.port: '{{ morla_prowlarr_exposed_proxy_port }}'
    traefik.http.routers.prowlarr.tls: true
    traefik.http.routers.prowlarr.rule: Host(`{{ morla_prowlarr_public_url }}`)
    traefik.http.routers.prowlarr.entrypoints: websecure
    traefik.http.routers.prowlarr.tls.certresolver: myresolver
    traefik.http.routers.prowlarr.tls.domains: '{{ morla_prowlarr_public_url }}'
