---
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init_flag.yml"

- name: Check if Config dir exists
  stat:
    path: "{{ morla_navidrome_config_dir }}"
  register: check_navidrome_config_dir

