---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_navidrome_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_navidrome_config_dir.stat.exists

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_navidrome_container_name }}'
          image: '{{ morla_navidrome_container_image}}'
          network: morla-wireguard-network
          network_aliases: '{{ morla_navidrome_short_name }}'
          ports: '{{ morla_navidrome_ports }}'
          volumes: '{{ morla_navidrome_volumes }}'
          labels: '{{ morla_navidrome_labels }}'
          user: '0:0'
          env:
              TZ: '{{ morla_tz }}'
              ND_SCANSCHEDULE: '{{ morla_navidrome_env_nd_scanschedule }}'
              ND_LOGLEVEL: '{{ morla_navidrome_env_nd_loglevel }}'
              ND_SESSIONTIMEOUT: '{{ morla_navidrome_env_nd_sessiontimeout }}'
              ND_BASEURL: '{{ morla_navidrome_env_nd_baseurl }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
