---
morla_jellyfin_enabled: true

morla_jellyfin_flag_public: true
morla_jellyfin_flag_autostart: true
morla_jellyfin_flag_wireguard: true
morla_jellyfin_flag_firewall: true # replace with if port list non empty

morla_jellyfin_long_name: Jellyfin
morla_jellyfin_short_name: jellyfin

morla_jellyfin_container_short_name: '{{ morla_jellyfin_short_name }}'
morla_jellyfin_container_name: '{{ morla_user_username }}-{{ morla_jellyfin_container_short_name }}'

morla_jellyfin_public_url: '{{ morla_jellyfin_short_name }}.{{ morla_public_url }}'

# filesystem dir for configs
morla_jellyfin_config_dir: '{{ morla_config_dir }}/{{ morla_jellyfin_long_name }}'
morla_jellyfin_media_dir: '{{ morla_media_dir }}'

morla_jellyfin_container_image_base: lscr.io/linuxserver/jellyfin
morla_jellyfin_container_image_tag: latest
morla_jellyfin_container_image: '{{ morla_jellyfin_container_image_base }}:{{ morla_radarr_container_image_tag }}'

morla_jellyfin_labels:
    traefik.enable: true
    traefik.http.services.jellyfin.loadbalancer.server.port: '{{ morla_jellyfin_reverse_proxy_port }}'
    traefik.http.routers.jellyfin.tls: true
    traefik.http.routers.jellyfin.rule: Host(`{{ morla_jellyfin_public_url }}`)
    traefik.http.routers.jellyfin.entrypoints: websecure
    traefik.http.routers.jellyfin.tls.certresolver: myresolver

# used inside container config
morla_jellyfin_reverse_proxy_port: '8096'
morla_jellyfin_internal_ip: 172.20.0.80

morla_jellyfin_fw_ports:
    tcp:
        - '8096'
        - '8920'
    udp:
        - '7359'
        - '1900'

morla_jellyfin_ports:
    - 8096:8096
    - 8920:8920
    - 7359:7359/udp
    - 1900:1900/udp

morla_jellyfin_volumes:
    - '{{ morla_jellyfin_config_dir }}:/config:Z'
    - '{{ morla_jellyfin_media_dir }}:/data/media:z'
