---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_hedgedoc_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_hedgedoc_config_dir.stat.exists

    - name: Create DB config directory
      ansible.builtin.file:
          path: '{{ morla_hedgedoc_db_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_hedgedoc_db_config_dir.stat.exists

    - name: Create pod
      containers.podman.podman_pod:
          name: '{{ morla_hedgedoc_pod_name }}'
          network: morla-wireguard-network
          ports: '{{ morla_hedgedoc_ports }}'
          label: '{{ morla_hedgedoc_labels }}'
          generate_systemd:
              path: '{{ morla_home_config_systemd_dir }}'
              restart_policy: always
              names: true
          state: started

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_hedgedoc_container_name }}'
          image: '{{ morla_hedgedoc_container_image}}'
          pod: '{{ morla_hedgedoc_pod_name }}'
          volumes: '{{ morla_hedgedoc_volumes }}'
          env:
              PUID: '{{ morla_root_puid }}'
              PGID: '{{ morla_root_pgid }}'
              TZ: '{{ morla_tz }}'
              # SSL options
              CMD_DOMAIN: '{{ morla_hedgedoc_public_url }}'
              CMD_URL_ADDPORT: false
              CMD_PROTOCOL_USESSL: true
              # DB options
              CMD_DB_PORT: '{{ morla_hedgedoc_db_env_port }}'
              CMD_DB_USERNAME: '{{ morla_hedgedoc_db_env_user }}'
              CMD_DB_PASSWORD: '{{ morla_hedgedoc_db_env_password}}'
              CMD_DB_HOST: localhost
              CMD_DB_DATABASE: '{{ morla_hedgedoc_db_env_db }}'
              CMD_DB_DIALECT: postgres
              # Auth methods
              # CMD_GITHUB_CLIENTID: "{{ morla_hedgedoc_auth_github_clientid }}"
              # CMD_GITHUB_CLIENTSECRET: "{{ morla_hedgedoc_auth_github_clientsecret }}"
              CMD_ALLOW_EMAIL_REGISTER: false
              # Security options
              CMD_CSP_ALLOW_FRAMING: false
              CMD_CSP_ALLOW_PDF_EMBED: false
          state: started

    - name: Create Database
      containers.podman.podman_container:
          name: '{{ morla_hedgedoc_db_container_name }}'
          image: '{{ morla_hedgedoc_db_container_image }}'
          pod: '{{ morla_hedgedoc_pod_name }}'
          network: container:morla-hedgedoc
          volumes: '{{ morla_hedgedoc_db_volumes }}'
          env:
              PUID: '{{ morla_root_puid }}'
              PGID: '{{ morla_root_pgid }}'
              TZ: '{{ morla_tz }}'
              POSTGRES_USER: '{{ morla_hedgedoc_db_env_user }}'
              POSTGRES_PASSWORD: '{{ morla_hedgedoc_db_env_password }}'
              POSTGRES_DB: '{{ morla_hedgedoc_db_env_db }}'
          state: started
