---
# roles/discord_soundboard_bot/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      when: morla_discord_soundboard_bot_enabled | bool
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      when: morla_discord_soundboard_bot_enabled | bool
      tags:
          - always
          - setup-all
          - setup-discord-soundboard-bot

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_discord_soundboard_bot.yml'
      when: morla_discord_soundboard_bot_enabled | bool
      tags:
          - setup-all
          - setup-discord-soundboard-bot

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_discord_soundboard_bot.yml'
      when: morla_discord_soundboard_bot_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-discord-soundboard-bot

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_discord_soundboard_bot.yml'
      when: morla_discord_soundboard_bot_enabled | bool
      tags:
          - setup-all
          - setup-discord-soundboard-bot
