---
    - name: Add Container to the list of autostart pods
      ansible.builtin.set_fact:
          morla_systemd_autostart_pods: '{{ morla_systemd_autostart_pods + [ morla_lychee_pod_name ] }} '
      when: ( morla_lychee_flag_autostart is defined ) and ( morla_lychee_flag_autostart|bool == True )

    - name: Add Container to the list of Firewall Services
      ansible.builtin.set_fact:
          morla_firewall_services: "{{ morla_firewall_services + [ { 'name': morla_lychee_short_name, 'ports': morla_lychee_fw_ports } ]}}"
      when: ( morla_lychee_flag_firewall is defined ) and ( morla_lychee_flag_firewall|bool == True )
