---
# roles/lychee/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      tags:
          - setup-all
          - setup-lychee

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_lychee.yml'
      when: morla_lychee_enabled | bool
      tags:
          - setup-all
          - setup-lychee

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_lychee.yml'
      when: morla_lychee_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-lychee

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_lychee.yml'
      when: morla_lychee_enabled | bool
      tags:
          - setup-all
          - setup-lychee
