---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_lychee_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_lychee_config_dir.stat.exists

    - name: Create DB config directory
      ansible.builtin.file:
          path: '{{ morla_lychee_db_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_lychee_db_config_dir.stat.exists

    - name: Create pod
      containers.podman.podman_pod:
          name: '{{ morla_lychee_pod_name }}'
          network: morla-wireguard-network
          ports: '{{ morla_lychee_ports }}'
          label: '{{ morla_lychee_labels }}'
          uidmap:
              - '{{ morla_fake_puid }}:0:1'
              - 0:1:{{ morla_fake_puid }}
              - '{{ morla_fake_puid + 1 }}:{{ morla_fake_puid + 1 }}:{{ morla_subuid_size - morla_fake_puid }}'
          gidmap:
              - '{{ morla_fake_pgid }}:0:1'
              - 0:1:{{ morla_fake_pgid }}
              - '{{ morla_fake_pgid + 1 }}:{{ morla_fake_pgid + 1 }}:{{ morla_subgid_size - morla_fake_pgid }}'
          generate_systemd:
              path: '{{ morla_home_config_systemd_dir }}'
              restart_policy: always
              names: true
              pod_prefix: '{{ morla_systemd_service_pod_prefix }}'
          state: started

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_lychee_container_name }}'
          image: '{{ morla_lychee_container_image}}'
          pod: '{{ morla_lychee_pod_name }}'
          volumes: '{{ morla_lychee_volumes }}'
          env:
              PUID: '{{ morla_fake_puid }}'
              PGID: '{{ morla_fake_pgid }}'
              TZ: '{{ morla_tz }}'
              DB_DATABASE: '{{ morla_lychee_db_env_mysql_database }}'
              DB_USERNAME: '{{ morla_lychee_db_env_mysql_user }}'
              DB_PASSWORD: '{{ morla_lychee_db_env_mysql_password }}'
              DB_HOST: localhost
              DB_PORT: 3306
          state: started

    - name: Create Database
      containers.podman.podman_container:
          name: '{{ morla_lychee_db_container_name }}'
          image: '{{ morla_lychee_db_container_image }}'
          pod: '{{ morla_lychee_pod_name }}'
          network: container:morla-lychee
          volumes: '{{ morla_lychee_db_volumes }}'
          env:
              PUID: '{{ morla_fake_puid }}'
              PGID: '{{ morla_fake_pgid }}'
              TZ: '{{ morla_tz }}'
              MYSQL_USER: '{{ morla_lychee_db_env_mysql_user }}'
              MYSQL_PASSWORD: '{{ morla_lychee_db_env_mysql_password }}'
              MYSQL_DATABASE: '{{ morla_lychee_db_env_mysql_database }}'
              MYSQL_ROOT_PASSWORD: '{{ morla_lychee_db_env_mysql_root_password }}'
          state: started
