---
    - name: Create config directory
      ansible.builtin.file:
          path: '{{ morla_ghost_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_ghost_config_dir.stat.exists

    - name: Create DB config directory
      ansible.builtin.file:
          path: '{{ morla_ghost_db_config_dir }}'
          state: directory
          owner: '{{ morla_user_username }}'
          group: '{{ morla_user_groupname }}'
      when: not check_ghost_db_config_dir.stat.exists

    - name: Create pod
      containers.podman.podman_pod:
          name: '{{ morla_ghost_pod_name }}'
          network: morla-wireguard-network
          ports: '{{ morla_ghost_ports }}'
          label: '{{ morla_ghost_labels }}'
          state: quadlet
          quadlet_options:
            - |
              [Install]
              WantedBy=default.target

    - name: Create Database
      containers.podman.podman_container:
          name: '{{ morla_ghost_db_container_name }}'
          image: '{{ morla_ghost_db_container_image }}'
          pod: '{{ morla_ghost_pod_name }}'
          volumes: '{{ morla_ghost_db_volumes }}'
          env:
              PUID: '{{ morla_user_puid }}'
              PGID: '{{ morla_user_pgid }}'
              TZ: '{{ morla_tz }}'
              MYSQL_DATABASE: '{{ morla_ghost_db_env_mysql_database }}'
              MYSQL_ROOT_PASSWORD: '{{ morla_ghost_db_env_mysql_root_password }}'
              MYSQL_USER: ghost
              MYSQL_PASSWORD: '{{ morla_ghost_db_env_mysql_password }}' 
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target

    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_ghost_container_name }}'
          image: '{{ morla_ghost_container_image}}'
          pod: '{{ morla_ghost_pod_name }}'
          volumes: '{{ morla_ghost_volumes }}'
          env:
              #NODE_ENV: development
              TZ: '{{ morla_tz }}'
              url: 'https://{{ morla_ghost_public_url }}'
              database__client: mysql
              database__connection__host: morla-ghost-db
              database__connection__user: ghost
              # database__connection__password: '{{ morla_ghost_db_env_mysql_root_password }}'
              database__connection__password: '{{ morla_ghost_db_env_mysql_password }}' 
              database__connection__database: '{{ morla_ghost_db_env_mysql_database }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
