- name: Close TCP ports for Wireguard
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: disabled
    immediate: true
  loop: "{{ morla_wireguard_fw_ports.tcp if morla_wireguard_fw_ports.tcp is iterable else []}}"

- name: Close UDP ports for Wireguard
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: disabled
    immediate: true
  loop: "{{ morla_wireguard_fw_ports.udp if morla_wireguard_fw_ports.udp is iterable else []}}"

