---
# roles/wireguard/tasks/main.yml
    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init_flag.yml'
      tags:
          - setup-all
          - setup-wireguard

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/pull_wireguard.yml'
      when: morla_wireguard_enabled | bool
      tags:
          - setup-all
          - setup-wireguard

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_wireguard.yml'
      when: morla_wireguard_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-wireguard

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_wireguard.yml'
      when: morla_wireguard_enabled | bool
      tags:
          - setup-all
          - setup-wireguard
