- name: Create Morla Wireguard Network
  containers.podman.podman_network:
    name: morla-wireguard-network
    subnet: 172.20.0.0/24
    driver: bridge 

- name: Crete Morla Wireguard Pod
  containers.podman.podman_pod:
    name: morla-wireguard-pod
    state: started
    network: 
      - morla-wireguard-network
    ports: "{{ morla_wireguard_ports }}"
    generate_systemd:
      path: "{{ morla_home_config_systemd_dir }}"
      restart_policy: always
      names: true
    uidmap:
      - "{{ morla_fake_puid }}:0:1"
      - "0:1:{{ morla_fake_puid }}"
      - "{{ morla_fake_puid + 1 }}:{{ morla_fake_puid + 1 }}:{{ morla_subuid_size - morla_fake_puid }}"
    gidmap:
      - "{{ morla_fake_pgid }}:0:1"
      - "0:1:{{ morla_fake_pgid }}"
      - "{{ morla_fake_pgid + 1 }}:{{ morla_fake_pgid + 1 }}:{{ morla_subgid_size - morla_fake_pgid }}"

- name: Create container
  containers.podman.podman_container:
    name: "{{ morla_wireguard_container_name }}"
    image: "{{ morla_wireguard_container_image}}"
    volumes: "{{ morla_wireguard_volumes }}"
    privileged: "{{ morla_wireguard_privileged }}"
    env:
      PUID: "{{ morla_fake_puid }}"
      PGID: "{{ morla_fake_pgid }}"
      TZ: "{{ morla_tz }}"
      SERVERURL: "{{ morla_wireguard_env_serverurl }}"
      SERVERPORT: "{{ morla_wireguard_external_server_port }}"
      PEERS: "{{ morla_wireguard_env_peers }}"
      ALLOWEDIPS: "{{ morla_wireguard_env_allowedips }}"
      LOG_CONFS: false
    cap_add: "{{ morla_wireguard_cap_add }}"
    pod: morla-wireguard-pod
    state: started
    restart_policy: unless-stopped
    generate_systemd:
      path: "{{ morla_home_config_systemd_dir }}"
      restart_policy: always
      names: true
      container_prefix: "{{ morla_systemd_service_prefix }}"

