---
    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_wireguard_container_name }}'
          image: '{{ morla_wireguard_container_image}}'
          network: morla-wireguard-network
          ports: '{{ morla_wireguard_ports }}'
          volumes: '{{ morla_wireguard_volumes }}'
          label: '{{ morla_wireguard_labels }}'
          privileged: '{{ morla_wireguard_privileged }}'
          cap_add: '{{ morla_wireguard_cap_add }}'
          sysctl:
              net.ipv4.ip_forward: 1
          env:
              PUID: '{{ morla_fake_puid }}'
              PGID: '{{ morla_fake_pgid }}'
              TZ: '{{ morla_tz }}'
              SERVERURL: '{{ morla_wireguard_env_serverurl }}'
              SERVERPORT: '{{ morla_wireguard_external_server_port }}'
              PEERS: '{{ morla_wireguard_env_peers }}'
              ALLOWEDIPS: '{{ morla_wireguard_env_allowedips }}'
              LOG_CONFS: false
          uidmap:
              - '{{ morla_fake_puid }}:0:1'
              - 0:1:{{ morla_fake_puid }}
              - '{{ morla_fake_puid + 1 }}:{{ morla_fake_puid + 1 }}:{{ morla_subuid_size - morla_fake_puid }}'
          gidmap:
              - '{{ morla_fake_pgid }}:0:1'
              - 0:1:{{ morla_fake_pgid }}
              - '{{ morla_fake_pgid + 1 }}:{{ morla_fake_pgid + 1 }}:{{ morla_subgid_size - morla_fake_pgid }}'
          state: quadlet
          quadlet_options:
            - "AutoUpdate=registry"
            - "Pull=newer"
            - |
              [Install]
              WantedBy=default.target
