---
# roles/gandi_ddns/tasks/main.yml


    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/init.yml'
      when: morla_gandi_ddns_enabled | bool
      tags:
          - always

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/build_gandi_ddns.yml'
      when: morla_gandi_ddns_enabled | bool
      tags:
          - setup-all
          - setup-gandi-ddns

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/destroy_gandi_ddns.yml'
      when: morla_gandi_ddns_enabled | bool
      tags:
          - never
          - destroy-all
          - destroy-gandi-ddns

    - ansible.builtin.import_tasks: '{{ role_path }}/tasks/setup_gandi_ddns.yml'
      when: morla_gandi_ddns_enabled | bool
      tags:
          - setup-all
          - setup-gandi-ddns
