---
    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_gandi_ddns_container_name }}'
          image: '{{ morla_gandi_ddns_container_image}}'
          env:
              PUID: '{{ morla_root_puid }}'
              PGID: '{{ morla_root_pgid }}'
              TZ: '{{ morla_tz }}'
          state: present

    - name: Install cronjob to check DNS twice a day
      ansible.builtin.cron:
          name: Check DNS for {{ morla_domain }}
          minute: 12
          hour: 10,22
          job: /usr/bin/podman run --rm -e GANDY_KEY={{ morla_letsencrypt_gandi_api_key }} -e GANDI_DOMAIN={{ morla_domain }} localhost/{{ morla_gandi_ddns_container_image
              }}
      register: check_cron_dns

    - name: Restart service cron, also issue daemon-reload
      become: true
      ansible.builtin.systemd:
          state: restarted
          daemon_reload: yes
          name: crond
      when: check_cron_dns.changed
