---
    - name: Create container
      containers.podman.podman_container:
          name: '{{ morla_traefik_container_name }}'
          image: '{{ morla_traefik_container_image}}'
          volumes: '{{ morla_traefik_volumes }}'
          ports: '{{ morla_traefik_ports }}'
          env:
              PUID: '{{ morla_fake_puid }}'
              PGID: '{{ morla_fake_pgid }}'
              TZ: '{{ morla_tz }}'
              GANDIV5_API_KEY: '{{ morla_traefik_env_gandiv5_api_key }}'
          uidmap:
              - '{{ morla_fake_puid }}:0:1'
              - 0:1:{{ morla_fake_puid }}
              - '{{ morla_fake_puid + 1 }}:{{ morla_fake_puid + 1 }}:{{ morla_subuid_size - morla_fake_puid }}'
          gidmap:
              - '{{ morla_fake_pgid }}:0:1'
              - 0:1:{{ morla_fake_pgid }}
              - '{{ morla_fake_pgid + 1 }}:{{ morla_fake_pgid + 1 }}:{{ morla_subgid_size - morla_fake_pgid }}'
          command: '{{ morla_traefik_command }}'
          label: '{{ morla_traefik_labels }}'
          security_opt: '{{ morla_traefik_security_opt }}'
          network: morla-wireguard-network
          state: started
          restart_policy: unless-stopped
          generate_systemd:
              path: '{{ morla_home_config_systemd_dir }}'
              restart_policy: always
              names: true
              container_prefix: '{{ morla_systemd_service_prefix }}'
