# roles/readarr/tasks/main.yaml

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/init.yaml"
  tags:
    - always

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/pull_readarr.yaml"
  when: "morla_readarr_enabled | bool"
  tags:
    - setup-all
    - setup-readarr

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/destroy_readarr.yaml"
  when: "morla_readarr_enabled | bool"
  tags:
    - never
    - destroy-all
    - destroy-readarr

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_readarr.yaml"
  when: "morla_readarr_enabled | bool"
  tags:
    - setup-all
    - setup-readarr

